-- Deliberately empty. Database setup does not create demo authentication users.
-- Use npm run preview:client for fictional accounts and sample submissions.
-- Never seed shared passwords or real operator identities into a hosted project.
