import type { Metadata } from 'next'
import Link from 'next/link'
import { LegalPage } from '@/components/shared/legal-page'
import { LEGAL } from '@/lib/legal'

export const metadata: Metadata = { title: 'Terms of use' }

export default function TermsPage() {
  return <LegalPage title="Terms of use" description={`How advisers and clients may use FactFind Pro, operated by ${LEGAL.operator} trading as ${LEGAL.tradingAs}.`}>
    <section><h2>1. What the service does</h2><p>FactFind Pro helps advisers collect information from clients, review completed forms and create PDF copies. It does not make mortgage, insurance, medical or suitability decisions. Your adviser remains responsible for checking the information and for any advice they give.</p></section>
    <section><h2>2. Adviser accounts</h2><p>Register with accurate details and an email address you control. Access is subject to approval by the platform administrator. Keep your password private and tell us promptly if you suspect someone else has accessed your account.</p><p>Each approved adviser has their own workspace and client links. Adding a colleague to your directory does not create an account or give that person access to client information. They must register separately.</p></section>
    <section><h2>3. Client information</h2><p>Only collect or upload information you are authorised to handle. Explain to clients why you need it and provide your firm’s privacy information. Check that you have the necessary permissions before entering information about a joint applicant, family member or another person.</p><p>Clients should give accurate answers and contact their adviser if an answer needs correcting. A submitted form is a record of the information provided; it is not an application approval, insurance cover or a recommendation.</p></section>
    <section><h2>4. PDFs and email preferences</h2><p>Advisers choose whether completed forms trigger adviser and client PDF emails. Authorised advisers can also send a client copy manually. Check the recipient’s address before sending. Once a PDF is emailed or downloaded, its recipient is responsible for storing and sharing that copy appropriately.</p><p>Email acceptance by the sending provider does not guarantee inbox delivery. If an expected copy does not arrive, check the dashboard and contact your adviser or platform support.</p></section>
    <section><h2>5. Responsible use</h2><p>Do not use the service to access another adviser’s records, submit fraudulent information, send unsolicited messages, distribute harmful files or interfere with the platform. We may restrict or suspend access to investigate misuse or protect accounts and client information.</p></section>
    <section><h2>6. Availability and records</h2><p>The service depends on hosting, database and email providers and may be interrupted. Unfinished answers are not currently saved for later recovery. Keep copies of completed records where your firm’s procedures require them.</p><p>Completed client records are retained until deletion is requested and processed, subject to any applicable legal requirement to retain particular information. There is no automatic 90-day deletion. Archiving a submission does not delete it. Advisers must review whether their records are still needed and request deletion when appropriate. See the <Link href="/privacy#retention">retention and deletion information</Link> for how to make a request.</p></section>
    <section><h2>7. Privacy and changes</h2><p>Read the <Link href="/privacy">Privacy notice</Link> for how information is handled. We may update these terms as the service changes. The version and date appear above. These terms do not replace an adviser’s obligations to their clients or any separate agreement with Wealthy Advisers Club.</p></section>
  </LegalPage>
}
